# Generated by Django 3.1.2 on 2021-10-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('hexadecimal_color', models.CharField(max_length=7, null=True)),
            ],
            options={
                'db_table': 'type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('is_default', models.BooleanField()),
                ('types', models.ManyToManyField(to='pokeapi.Type')),
            ],
            options={
                'db_table': 'pokemon',
                'ordering': ['name'],
            },
        ),
    ]
